
import Head from 'next/head'
import React from 'react'
import Header from './Header'
import LeftAside from './LeftAside'
import RightAside from './RightAside'
import Footer from './Footer'

export default function CommonLayout({children}) {
  return (
    <>
      <Head>
        <title>27 Sep 2023 Day-13</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='container-fluid'>

        <Header />

        <main className='row'>
          <LeftAside />
            {children}
          <RightAside />
        </main>

        <Footer />

      </div>

    </>
  )
}
